### ISSUE TITLE
open links in new tabs

### ISSUE THREAD

**Issue by benaryorg** [llelectronics/webcat#13]
I have set Webcat as my standard browser as discussed here:
https://together.jolla.com/question/1836/set-default-browser/

If the browser is already running it does not open anything (as the main() was already called).

**Comment by llelectronics** [comment]
Yeah indeed a limitation. Not sure how to fix this though.

**Comment by benaryorg** [comment]
I will look into it, but I do not really have time for a few weeks now.

However, you might find an app which does have this feature.

**Comment by benaryorg** [comment]
In relation: https://github.com/Dax89/harbour-webpirate/issues/7

**Comment by llelectronics** [comment]
This commit: https://github.com/llelectronics/webcat/commit/c09911b4d1abc4a3dd67116994bf315c29825861
Addes support for dbus protocol. 
So if you correctly copy the the dbus service file included into that commit to ~/.local/share/dbus-1/services and adapt the open-url.desktop like so (could be also put into ~/.local/share/applications/):

    [Desktop Entry]
    Type=Application
    Name=Browser
    NotShowIn=X-MeeGo;
    MimeType=text/html;x-maemo-urischeme/http;x-maemo-urischeme/https;
    X-Maemo-Service=org.harbour.webcat
    X-Maemo-Method=org.harbour.webcat.openUrl

it should work just like the sailfish-browser. (Though Webcat always tries to load the homepage in one tab when closed previously which causes a blank first tab)

I hope I can integrate that into the browser somehow or come up with another solution for the mimer app I wrote.

**Comment by llelectronics** [comment]
This is now closed with this commit: https://github.com/llelectronics/webcat/commit/576a33118eb681e0b63e5156f582169994c1a235
