### ISSUE TITLE
PixelRatio Hack: Blacklist dailymotion

### ISSUE THREAD

**Issue by Dax89** [llelectronics/webcat#16]
www.dailymotion.com is displayed with a black band on the right.
Blacklisting the website in the pixel ratio's script fixes the issue :)

**Comment by llelectronics** [comment]
I don't get a black band on the right. Just the normal mobile site. See screenshot: http://abload.de/image.php?img=201503031145433ls0i.png

**Comment by Dax89** [comment]
I have tried to disable all users scripts, including the grabber, leaving only the pixel ratio hack enabled, but the result is the same.

This is what happens:
https://dl.dropboxusercontent.com/u/40206233/Screenshots/WebPirate/20150303121029.jpg

The issue should be somewhere in my browser, I will investigate on that!
Thanks :)
