### ISSUE TITLE
Сonfigurable cover actions

### ISSUE THREAD

**Issue by lewadedun** [llelectronics/webcat#18]
What do you think about this?

**Comment by llelectronics** [comment]
This needs some code restructioning and tons of options that need to be implemented. 
So keep it simple is better I guess.

**Comment by lewadedun** [comment]
But very handy when you have multiple tabs open. You can change and view the page without opening a browser. I think this will be especially on the tablet.

**Comment by llelectronics** [comment]
Yeah you are right this feature will be useful on the tablet. 
I will take a look at it. But as I was informed the API changes a little in SailfishOS 2.0 I will wait with the implementation until its out.

**Comment by lewadedun** [comment]
Ok!

**Comment by Caballlero** [comment]
llelectronics  any plans of  this ?  will nice if Implemented ...
