### ISSUE TITLE
Proxy Support (Workaround)

### ISSUE THREAD

**Issue by Dax89** [llelectronics/webcat#23]
Hi @llelectronics 

I have found a workaround in order to enable Proxy Support, look this commit: https://github.com/Dax89/harbour-webpirate/commit/31519cca5c53d01bcc317d913c88d34bf751b5bc

Fell free to use the implementation in WebCat!

(There is also WebP support for the WebView, in the previous commit, if you're interested :))

**Comment by llelectronics** [comment]
Thanks. I will take a look at it when I find some time :)

**Comment by Dax89** [comment]
:+1:

**Comment by llelectronics** [comment]
Added Proxy support now in latest commit 
https://github.com/llelectronics/webcat/commit/48f2c473940e382b062971b700ff2cec655ad6a2
Thanks again for that great code ;)
