### ISSUE TITLE
Problems with lists

### ISSUE THREAD

**Issue by lewadedun** [llelectronics/webcat#26]
https://github.com/Dax89/harbour-webpirate/issues/21

Same here

**Comment by Dax89** [comment]
@llelectronics you can fix in this way:

WebKit side:
https://github.com/Dax89/harbour-webpirate/blob/master/harbour-webpirate/qml/js/helpers/WebViewHelper.js#L111

Qml side:
1. https://github.com/Dax89/harbour-webpirate/blob/master/harbour-webpirate/qml/components/browsertab/webview/WebViewListener.qml#L66
2. https://github.com/Dax89/harbour-webpirate/blob/master/harbour-webpirate/qml/components/browsertab/webview/BrowserWebView.qml#L13

**Comment by llelectronics** [comment]
Thanks for the info :)

**Comment by lewadedun** [comment]
Unfortunately, the problem remained...
For example:
http://pda.finam.ru/analysis/charts/?id=795
v.2.2.1

**Comment by llelectronics** [comment]
It works here.

**Comment by lewadedun** [comment]
Try it a few times. Does not always work.

**Comment by lewadedun** [comment]
reproduce.
1. Open pda.finam.ru
2. click any link
![20160408070934](https://cloud.githubusercontent.com/assets/9382415/14372994/2141ca84-fd5f-11e5-8dec-f8b113f5c39b.jpg)
3. see that the browser does not remember position in list
![20160408070957](https://cloud.githubusercontent.com/assets/9382415/14373007/42a2fbc6-fd5f-11e5-91d6-5dc79e6998d4.jpg)
4. and another little bug
![20160408071041](https://cloud.githubusercontent.com/assets/9382415/14373013/5af872d2-fd5f-11e5-823b-a0339934c3e7.jpg)

**Comment by llelectronics** [comment]
I think I get now what you meant. Though I guess this is a webkit issue as it does not seem to refresh after a change is done always. (a item is clicked from the list) 
I don't see any issue with the way the popover is implemented on my site.
