### ISSUE TITLE
Proxy auto-config support

### ISSUE THREAD

**Issue by strixaluco** [llelectronics/webcat#28]
Thank you for developing Webcat, it does have less problems rendering websites, comparing to the stock SFOS browser.
And it will be even more great if Webcat could support proxy auto-config. 
Any ideas about feasibility of this feature?

**Comment by llelectronics** [comment]
This needs manual implementation. So hard to do and I don't think it will come any time soon. 
The current implementation of Proxy is sort of a hack already as it is using shell variables only.

**Comment by strixaluco** [comment]
It's a pity, but thanks for explanation.
