### ISSUE TITLE
I can't play videos from RTVE (Spanish canal)

### ISSUE THREAD

**Issue by carmenfdezb** [llelectronics/webcat#29]
I can't play videos from this link:
http://www.rtve.es/directo/la-1/

However, I have no problems with webpirate neither browser jolla.

I will appreciate a lot if you fix this issue. 
Thanks in advance.

**Comment by llelectronics** [comment]
I can't play anything aswell. The root cause is the missing html5 audio/video support of qtwebkit.
So WebPirate doesn't work here aswell. 
Even the Sailfish Browser is giving me a mime type error on most of the videos there.
