### ISSUE TITLE
Some websites render incorrectly

### ISSUE THREAD

**Issue by Sami-Perkele** [llelectronics/webcat#3]
Some websites are rendered wrong. They are shown correctly on native Sailfish browser, Chromium and Firefox, but WebCat shows them wrong.

Examples:
http://kuvaton.com/
http://avaxhome.cc/

**Comment by llelectronics** [comment]
I think that can be closed now kuvaton.com is now rendering and the other site isn't online anymore.

**Comment by Sami-Perkele** [comment]
AvaxHome has changed it’s address to http://avaxhm.com/

**Comment by llelectronics** [comment]
Ok AvaxHome looks bad thats clear. However I cannot do anything about it currently. In its core its a webkit rendering problem so not particular related to webcats code.
