### ISSUE TITLE
webkit---chromium

### ISSUE THREAD

**Issue by Caballlero** [llelectronics/webcat#35]
Hi leszek
Just wanted to know if webcat is going to stay with webkit oh there plans to Qt WebEngine  ? with the new framework qt5.6 that includes Qt WebEngine by default. i am a little confuced about

**Comment by llelectronics** [comment]
I am not seeing QtWebengine being included in SailfishOS 2.1.0.9 . At least there is no package providing it. I need to take a look if it is really included at all. If it is not then I won't be able to port anything to Qtwebengine. 
Maybe Sailfish WebView based on the Gecko Engine is useful. I did not try that in regards of memory usage and speed yet.

**Comment by Caballlero** [comment]
yes, Qt WebEngine is not shipped in lijoki. so still webkitqt.5.6.  the true is that Qt WebEngine Was introduced in qt5.6 At the same time that it left to webkit in the same version ;  )  
#Then what improvements are expected in webcat lesner?

**Comment by Caballlero** [comment]
# THANKS, CLOSE THIS :  |
