### ISSUE TITLE
Adblocker support

### ISSUE THREAD

**Issue by Sami-Perkele** [llelectronics/webcat#4]
Some websites have so much advertises that it's hard to find the actual content. It would be very nice to have an adblocker in the browser.

**Comment by Dax89** [comment]
Today I have made this script: https://github.com/Dax89/harbour-webpirate/blob/master/qml/js/helpers/AdBlock.js

Tecnically it isn't an AdBlocking system but a simple blacklist one, it's still in its infancy, but it blocks some unwanted ads, currently the rules are hardcoded.

It's sufficient to call __wp_adblock__.blockAds() (you can change the prefix, if you want :P) when the page is loaded and the ads will be hidden, the commented code contains an object that allows to intercept Ajax requests done by the webpage, but it is untested.

**Comment by llelectronics** [comment]
Thx I will take a look at it. 
Main problem I see currently is the scalability. 
So the bigger the adblocking lists are the more ram the browser needs and the slower it will get. 
Maybe taking the lighter approach only blocking some ads (most of the annoying ones) is better here. Let's see :)

**Comment by Dax89** [comment]
I agree with you!
It's not possible to make a full fledged AdBlock without using a lot of ram.

**Comment by llelectronics** [comment]
Thx Dax89. Due to your excellent work I was also able to ad a simple adblocker to webcat. 
I added some more default rules to block some nasty ads I encountered on some sites.

**Comment by Dax89** [comment]
If you don't want to hardcode the rules, there is also the editor :)

C++ Side:
https://github.com/Dax89/harbour-webpirate/tree/master/src/adblock

Qml Side:
https://github.com/Dax89/harbour-webpirate/tree/master/qml/pages/adblock

**Comment by llelectronics** [comment]
Thanks again will take a look at it and maybe implement it. I rather want to keep this feature as simple and basic as possible though as I know from experience if you give users the chance to edit those filters they will add a whole lot of that with the potential to make the browser slow as hell :)
