### ISSUE TITLE
[Usability issue] Settings --> Backup manager does not properly support landscape orientation

### ISSUE THREAD

**Issue by Olf0** [llelectronics/webcat#43]
In Webcat 2.8-1 under SailfishOS 2.1.0.11 on a Jolla 1 phone, Settings --> Backup manager does not properly support landscape orientation:
- The page does not scroll, although it is too long to fit of the screen. 
- The backup notification is displayed "in portrait orientation", i.e. on the left side of the screen and rotated by 90°. 

Many thanks for this really cool web browser, especially its text selection capabilitiy and handling are unique and outstanding!

**Comment by llelectronics** [comment]
Thanks for reporting. 
Taking a look at that

**Comment by Olf0** [comment]
Thank you for fixing that so quickly.
