### ISSUE TITLE
Repainting problem

### ISSUE THREAD

**Issue by paulzey** [llelectronics/webcat#46]
Hello.
I found a problem after updating to SFOS 2.1.0.11 (Jolla Phone 1). Seems that browser sometimes forget to repaint the main window.
Steps:
1) Load some site (two screens long should be enough).
2) Switch to another app.
3) Switch back to the browser, scroll down.
Voilà, we have nice white space from some line till the bottom of the page (fig.1).

Now about repainting.
Page reloading won't help, even if other link (from current page) is visited - no repaints at all, but switching to the bookmarks window and back to tab does the trick (fig.2).

Best regards,

![fig_001](https://user-images.githubusercontent.com/30520625/28708737-6d47c112-738e-11e7-9120-632fca379b8f.png)
![fig_002](https://user-images.githubusercontent.com/30520625/28708738-6d481b94-738e-11e7-823b-0997b88fec11.png)

**Comment by llelectronics** [comment]
See this bug report here: https://together.jolla.com/question/143358/bug-202x-browser-rendering-cut/

**Comment by paulzey** [comment]
Well, I thought it was a low layer system bug but still have some hopes. Thank you!
Since there are no any specific solutions, I'd rather use workaround mentioned above. 
Thanks again.
