### ISSUE TITLE
Add some sentence if possible to  translate 

### ISSUE THREAD

**Issue by Caballlero** [llelectronics/webcat#47]
This sentences is only showed if webcat not have internet. It is good to add these strings to have a full complete translation.
![captura_20170729_001](https://user-images.githubusercontent.com/24536606/28746885-42f28f7c-7461-11e7-86b7-c758b4ad0945.png)

**Comment by llelectronics** [comment]
Those error messages are produced by the webkit engine itself. I cannot translate them from within webcat.

**Comment by Caballlero** [comment]
Ok what do we do with this issue? Close it or keep it Open?

**Comment by llelectronics** [comment]
Keep it open for now. As you see I tagged it upstream-issue and wontfix for now. 
On my first research there might be the possibility for custom error message implementation by reimplementing the html errorcode detection and assign translatable error messages to it. 
This is however a little bit of work.

**Comment by Caballlero** [comment]
OK thank you very much.

**Comment by Caballlero** [comment]
There are more here.
![captura_20170731_001](https://user-images.githubusercontent.com/24536606/28793101-e7b2747e-75ff-11e7-8e43-57dc1e011a9e.png)
  =  )

**Comment by Caballlero** [comment]
![captura_20170731_003](https://user-images.githubusercontent.com/24536606/28808029-27ed001c-7647-11e7-896a-73b40858528c.png)
![captura_20170731_004](https://user-images.githubusercontent.com/24536606/28808035-3380c5f8-7647-11e7-89fd-59f0cff835ce.png)
![captura_20170731_005](https://user-images.githubusercontent.com/24536606/28808040-39f59166-7647-11e7-9259-ec59d9df52f4.png)

**Comment by llelectronics** [comment]
Thanks again for reporting. Fixed those new mentions in this commit: https://github.com/llelectronics/webcat/commit/cbae0c3aa27f77e1fa4aa9642454fc452856b4f6

**Comment by Caballlero** [comment]
Ok , almost done! one string are missing to translate " Custom " on last picture(show above) " Custom - Agent of user "

**Comment by llelectronics** [comment]
Thanks for notifying fixed aswell with https://github.com/llelectronics/webcat/commit/865b1728ed7969b21d75aaed95616e6fa59f6d66

**Comment by Caballlero** [comment]
- Still missing some string to translate. " none
![captura_20170803_001](https://user-images.githubusercontent.com/24536606/28995816-48a255aa-79c1-11e7-89a4-3ffb651f5654.png)
 "

**Comment by Caballlero** [comment]
" play "
![captura_20170805_001](https://user-images.githubusercontent.com/24536606/28995835-8ae77558-79c1-11e7-870d-d35c8ddff179.png)

**Comment by Caballlero** [comment]
" Download "
![captura_20170805_002](https://user-images.githubusercontent.com/24536606/28995842-b1e1d9dc-79c1-11e7-9d88-8dfdd3663567.png)

**Comment by Caballlero** [comment]
![captura_20170804_001](https://user-images.githubusercontent.com/24536606/28995851-dcaf1120-79c1-11e7-9c30-dc6daabad84d.png)

**Comment by llelectronics** [comment]
Thanks updated here: https://github.com/llelectronics/webcat/commit/e2f3a101577f14d466a8d0e77f6d1a2ca40da31d

**Comment by Caballlero** [comment]
the thanks are for you.
