### ISSUE TITLE
"Proxy setting" not work on next release of webcat 

### ISSUE THREAD

**Issue by Caballlero** [llelectronics/webcat#50]
I just notifiying that after build webcat for testing , proxy setting not work.  **Does not open the settings window** for options.

**Comment by llelectronics** [comment]
Thanks for reporting fixed with https://github.com/llelectronics/webcat/commit/bc0f0fab36ec23c38427004f3cfffbf7c9c6cd35

**Comment by Caballlero** [comment]
I builded Webcat again with the new SDK-1707-Jämsänjoki. I can confirm that " proxy setting " **work perfect** and the rest . . .
