### ISSUE TITLE
Some sentences need optimization

### ISSUE THREAD

**Issue by Caballlero** [llelectronics/webcat#52]
- **Observe the two yellow lines below**, start badly, in this case that is spanish the phrase would be very large for a screen in vertical mode I do not know if in English the phrase would also be very large. It would be good to first fix the beginning of the sentence from left to right and then look for an optimized sentence.**( Issue in: Backup Manager Page )**
![captura_20170801_001](https://user-images.githubusercontent.com/24536606/28854455-2f37c37a-7705-11e7-8015-90cc43bbeada.png)
- Here in this mode same issue
![captura_20170801_001 1](https://user-images.githubusercontent.com/24536606/28854495-6b37aeb2-7705-11e7-8d0e-c4c564698f37.png)

**Comment by llelectronics** [comment]
Ah ok. Maybe the subheader silica element is not the best to use here for those long descriptions.

**Comment by Caballlero** [comment]
![captura_20170804_001](https://user-images.githubusercontent.com/24536606/28995866-2540a002-79c2-11e7-8fc6-d1203c19a8fd.png)

**Comment by llelectronics** [comment]
It looks fine to me. That's exactly what the patch does. Adding a second line for the section header.

**Comment by Caballlero** [comment]
Well ,it is look better then before. But the first letter of the sentence does not start glued to the left side, so it looks like a bad layout, that's my opinion, but the developer is you and you are the owner on any layout you wanna look. I'm doing and observing possible errors about the Browser in general only.
My suggestion: is that passing these sentences for the sentences below, would look more clean and optimized.  ??

**Comment by llelectronics** [comment]
I am using the default section silica element here and they have the text alignment set to right instead of left. 
I could change that though in general those should be only short section headers nothing more. Putting them in the the description does not make sense to me. 
I will allign them to the left and then we'll see.

**Comment by Caballlero** [comment]
Sound good! thank.

**Comment by llelectronics** [comment]
Done here https://github.com/llelectronics/webcat/commit/6d8f64977d2b9559390354d49709e57bc0173b19

**Comment by Caballlero** [comment]
Firts i will send a PR with all the translation,then i build webcat again to see  how looking.

**Comment by llelectronics** [comment]
It does not look ideal for those long translations in the section header. Though I have no other idea what to use instead.

**Comment by Caballlero** [comment]
ok . i apologize for my late reply, i was without internet for 48 hours

**Comment by Caballlero** [comment]
![captura_20170807_001](https://user-images.githubusercontent.com/24536606/29050678-8519263a-7bab-11e7-933a-63ab740f8be1.png)

**Comment by Caballlero** [comment]
What you thing?
