### ISSUE TITLE
Some options/sentences maybe not are very usefull

### ISSUE THREAD

**Issue by Caballlero** [llelectronics/webcat#53]
- In order to have this browser optimized, it is proposed if it would be better to remove this function from orientations, **and let sailfish choose the orientation**. The system has a dynamic orientation function, but if a person wants to keep the screen in vertical mode even when the phone is in horizontal mode it is not matter just of keeping the screen pressed before turning in any direction and the system will respond. Other than these strings are untranslated. It is better to remove this all, what do you think? **You have the last decision!**  :  )

![captura_20170802_001](https://user-images.githubusercontent.com/24536606/28877587-d952b292-776a-11e7-9a31-56ae6d4215c2.png)
![captura_20170802_002](https://user-images.githubusercontent.com/24536606/28877612-e4bf6454-776a-11e7-82e9-5928745904d1.png)

**Comment by llelectronics** [comment]
It was a feature request that's why the feature is build in. The strings cannot be translated as they are used directly as programm code.

**Comment by Caballlero** [comment]
Ok . I'm just helping by proposing ideas to improve webcat

**Comment by llelectronics** [comment]
Yes thanks for that. Nevertheless I will close this issue.

**Comment by Caballlero** [comment]
Okey dokey
