### ISSUE TITLE
Testing WC -v2.9.8 on  qtwebkit5.212

### ISSUE THREAD

**Issue by Caballlero** [llelectronics/webcat#56]
Hi llectronics.
i am testing WC-v2.9.7 with patched Qtwebkit,. Then i have some report . .

  1.  Html5 test: not give result
   2. Maemo talk: still have same issues to show page.
   3.Youtube.com: not work,look like it is in blacklist.
   4.Facebook.com: login unsuccess
   5.Patched Qtwebkit: look only 50% of a screen in sailbook.
   6.I feeling crashes when i was browsing .
   7. New tab(2/3/>): not work to go at any webpage.

**Comment by llelectronics** [comment]
2) the rendering thing I mentioned in my announcement for the last version is bound to the device pixel ratio hack. So Webkit update can't fix this. 
3) youtube loads fine here. 
4) I changed the default user agent for it. Though please try with one of the other user agents. The website it loads is bound to the user agent you choose.
5) Sailbooks deviceratiohack is not complete they seem to miss the overview experimental setting
6) you experienced crashing? On what pages? Can you reproduce this all the time or is it at random? Is it more crashy then the previous version? 

The last point I don't get. I have tried 6 Tabs here on the Jolla c and everything works. However the there is a bug in the suggestionbo not loading the clicked url.

**Comment by Caballlero** [comment]
2. ok
3. i do not know why for my not load. i will delete cookies ,maybe work.
4. ok i will try with other user agents.
5. ok it is fine. sailbook is watching on your obs changes on qtwebkit-patch.
6. ramdom pages, feeling freeze | a little more crashy then the previous version.(like freeze)
7. you right on new tab only work in bookmark ,but not typing in url. i cleared.

**Comment by Caballlero** [comment]
1..youtube.com is fixed deleting cookies.
2.. think that ulr bug is causing like the browser feel freeze or crash. i wil wait when it is fixed to test again. 
 3..about facebook.com i **only** get login success in n9 useragent. but after login the page look out of layout, unusable.
**n9 useragent after get login**
![captura_20170903_001](https://user-images.githubusercontent.com/24536606/30005963-1a4974c4-90bc-11e7-8f82-b5e1304780e4.png)

**Comment by Caballlero** [comment]
-- I have a question if I have to install all (qtwebkit)patched packages to mer-sdk ? to better performance to build WC starting -v2.9.7 ??

thnks.

**Comment by llelectronics** [comment]
Webcat uses qtwebkit runtime based. So you don't need to install it to mersdk.
Btw. the bug rearding urlbar suggestions is fixed by this: https://github.com/llelectronics/webcat/commit/96f1f9b5ca8ecd5d6d88198cd9a4a84e057a715e

I also prepared a little video demo on my SailfishOS App Podcast Youtube Playlist. Should be up any minute.

**Comment by Caballlero** [comment]
llelectronics you uploaded  SailfishOS App Podcast Youtube in **360P**?

**Comment by llelectronics** [comment]
Nope. Youtube apparently still converts in the background.

**Comment by Caballlero** [comment]
yes it is now fixed till top **1080p**

**Comment by Caballlero** [comment]
-- i already saw the podcast video(good demo), it is correct now webcat is much better before, but  qtwebkit 5212 engine will come with SFOS 2.1.2 ?

**Comment by llelectronics** [comment]
I will discuss this on the next community meeting. I guess it will not be able to enter for SailfishOS 2.1.2 but in a later version.

**Comment by Caballlero** [comment]
After a heavy use of WC,i do not get any crashes or freezes.
 With this commit made today, the WC feeling more smooth-fast-stable that before. it  still missing some features in WC to show some page in full like: http://html5test.com/ http://www.antutu.com/html5/ http://css3test.com/ http://acid3.acidtests.org/

**Comment by llelectronics** [comment]
Yes I am aware of this. Talked with the qtwebkit devs that told me it is a problem of the sites and can be solved by activating media source extension in the browser. However this option is not exposed to qml yet. I will try patching it and see if I can make it work.

**Comment by llelectronics** [comment]
Patched it and it works now. Will upload the new source so it will rebuild on merobs. After that see the new git webcat upload I did.

**Comment by Caballlero** [comment]
Nice! - I'm surprised about all the work you're doing.
I am doing an absolute research on the use of the User-Agent on a browser, and how this can impact on a browser depending on the configuration. this to have a idea(solve) why in WC in defauld jolla webkit not work facebook.

**Comment by Caballlero** [comment]
So it is already now new qtwebkit to download? then install it in my phone ?

**Comment by llelectronics** [comment]
Yes the build finished. You can download the new rpms.

**Comment by Caballlero** [comment]
# Before 
![captura_20170905_001](https://user-images.githubusercontent.com/24536606/30082569-4c7a9a74-9259-11e7-8435-7830d16ac1aa.png)

# After
![captura_20170905_002](https://user-images.githubusercontent.com/24536606/30082585-5c4bda94-9259-11e7-8843-39344d3e75d7.png)

**Comment by Caballlero** [comment]
llelectronics  **HTTPS everywhere(Like)** is failing very often

**Comment by llelectronics** [comment]
What do you mean? 
I know https everywhere but that's a plugin for gecko browsers.

**Comment by Caballlero** [comment]
I know that is a plugin for gecko browsers, that's why I wrote  "HTTPS everywhere**(Like)**" . This feature was integrated starting in **wc -v2..6 descrip: Updated SearchEngines to use https whenever possible**

**Comment by llelectronics** [comment]
I would not call that the dame as https everywhere or like as it is only setting all default search engines to use https instead of http. I am not sure what is failing there and what do you mean by often? Does it mean sometimes your searches don't work? Or are certain engines perhaps out of date?

**Comment by Caballlero** [comment]
I cleared. wc  work nice, it is only that some web page does not redirect to https. example: prensalibre.com

**Comment by Caballlero** [comment]
WC 2.9 **media-source-extension:unabled**
![captura_20170906_001](https://user-images.githubusercontent.com/24536606/30120068-cf59a29a-92f5-11e7-9466-07a8acbd83fb.png)

WC 2.9.7 nightly. **media-source-extension:enabled**
![captura_20170906_001 1](https://user-images.githubusercontent.com/24536606/30120134-ffbb5a78-92f5-11e7-8d86-a470e4617187.png)

**Comment by Caballlero** [comment]
![captura_20170905_001](https://user-images.githubusercontent.com/24536606/30136657-ed52131c-932d-11e7-8e4b-68709793ff90.png)
- clear cookies windows stay freeze.

**Comment by llelectronics** [comment]
Can you give me the console output when doing this please.

**Comment by Caballlero** [comment]
[nemo@Sailfish ~]$ harbour-webcat
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - 
WARNING: This project is using the experimental QML API extensions for QtWebKit and is therefore tied to a specific QtWebKit release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

[D] openNewTab:175 - openNewTab: pageU91jh, currentTab: 
[W] unknown:0 - QObject::connect: No such signal WebKit::QtWebPageEventHandler::pinching(bool)
[W] unknown:751 - file:///usr/share/harbour-webcat/qml/pages/FirstPage.qml:751:9: QML HorizontalScrollDecorator: Cannot anchor to an item that isn't a parent or sibling.
[W] unknown:0 - QQmlExpression: Expression file:///usr/lib/qt5/qml/Sailfish/Silica/SilicaWebView.qml:143:16 depends on non-NOTIFYable properties:
[W] unknown:0 -     QQuickWebViewExperimental::transparentBackground
[W] unknown:79 - file:///usr/lib/qt5/qml/Sailfish/Silica/SilicaWebView.qml:79: TypeError: Cannot read property 'orientation' of null
[D] onMessageReceived:467 - onMessageReceived: {"type":"iframe","isrc":"/post2.html"}
[D] expression for currentIndex:387 - [SettingsPage.qml] mainWindow.coverActiopnGroup:1
[D] expression for currentIndex:252 - [SettingsPage.qml] mainWindow.allowedOrientations:11
[W] unknown:38 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/Util.js:38: TypeError: Cannot read property 'parent' of null
[W] unknown:251 - file:///usr/share/harbour-webcat/qml/pages/SettingsPage.qml:251:31: Unable to assign [undefined] to int
[W] unknown:144 - file:///usr/share/harbour-webcat/qml/harbour-webcat.qml:144: TypeError: Property 'deleteAllCookies' of object QQuickWebViewExperimental(0xb7d93f40) is not a function

**Comment by Caballlero** [comment]
- User-agent: Customs, is broken too. **not save data**

**Comment by llelectronics** [comment]
Custom settings works but the word custom is translated that's why it does not save stuff if the setting is not translated. Solution is to use the translated UI then it should work.

**Comment by llelectronics** [comment]
Fix landed here: https://github.com/llelectronics/lls-qtwebkit/commit/872a30446d0644cf782463be6c53eea58df3584b 

Will retrigger a rebuild of the rpms on mer after some testing of gstreamer-gl and if it maybe makes video playback smoother.

**Comment by Caballlero** [comment]
sound good thank u.

**Comment by Caballlero** [comment]
llelectronic you know that the "cursor pointer" does not work properly?

**Comment by llelectronics** [comment]
You mean it goes to the start of a word you are typing? That is a known issue when spellcheck is turned on.

**Comment by Caballlero** [comment]
yes, will be  fixed that?

**Comment by llelectronics** [comment]
I don't see an option for this to switch it on or off in runtime. I have it on my todo list. Either fixing this or disabling it (during compile time) as there is an alternative input mode now in webcat for input and textareas by longpressing on them which uses a native silica inputbox which should always have spellchecking on.

**Comment by Caballlero** [comment]
But this issues does not exist in the old version of wc 2.9. why this new wc "nightly build" exist?
i will upload some screenshot.

**Comment by llelectronics** [comment]
It is an problem within qtwebkit and not webcat.

**Comment by Caballlero** [comment]
Ok . You say in the **new** qtwebkit5212 ?

**Comment by llelectronics** [comment]
Yes. The old has this feature turned off. Though Jolla wrote a patch to turn it on during runtime. I tried it there also back when they introduced it and it shows the same behavior.

**Comment by Caballlero** [comment]
I got it, thnk u .

**Comment by Caballlero** [comment]
Also why when i open **second tab** this not come with duckduckgo.com configured in settings-about:bookmark. **only work in first tab**?
**Edit:** Will by nice if it is fixed.

**Comment by Caballlero** [comment]
Actually wc look like **javascript** is disabled,   this makes the web2.0 be limited. as an example: http://acid3.acidtests.org/.

**Comment by llelectronics** [comment]
Javascript is enabled. Not sure what the acid test is complaining about. Without javascript almost every website would look broken.

**Comment by Caballlero** [comment]
Ok. It's strange, but the case of **"acid3 test"** it can be a demonstration that javascript does not work very well. as an example: the suddenly freezes of some pages.

**Comment by Caballlero** [comment]
**New tab reply:** okay, yes is is nice that **second tab** come with a setting as configured.

**Comment by llelectronics** [comment]
There is no settings for new tabs. New tabs open empty pages. That is how it should be.

**Comment by Caballlero** [comment]
Ok 
- You are doing a extraordinary work in wc, stay up.

**Comment by Caballlero** [comment]
**llelectronics** I think i already found the issue of **acid3 test-failed** we need **Enable Attributes: " HTML DOM2 Events "**, with this allow javascript work  sequentially then will fix many issues on web2.0 in this case at http://acid3.acidtests.org/.

**Comment by Caballlero** [comment]
- In this screenshot showed that javascript is  failed on "html dom1+ events"
![captura_20170910_001](https://user-images.githubusercontent.com/24536606/30247174-eb6d43b8-95db-11e7-9470-322fabb40917.png)

**Comment by Caballlero** [comment]
HI llelectronics, i am doing several user-agent testing, i getting great progress. but i noticed that some problems are affecting user-agent, " like pixelRatio as an exampl: m.google.com ".
I see that mostly mobile devices use PixelRatio **3**. to desktop PixelRatio **1**

**Comment by Caballlero** [comment]
Also "Web Pirate" **pass** all  http://html5test.com/ http://www.antutu.com/html5/ http://css3test.com/ http://acid3.acidtests.org/ 
It might be a good idea to reuse the webpirate JS code and use it in webcat to stabilize webcat. webpirate behaves more stable.

**Comment by llelectronics** [comment]
Pixel Ratio is something you need to set for every device differently. So the Pixel Ratio is set through a hack as Jolla refuses to set a global default Pixel Ratio for their Qt Platform (its always 1.0). 
The user agent might only affect the pixel ratio implicitly when set to a desktop browser for example which tries loading the desktop page instead of the mobile one. 
m.google.com is broken for me does basically nothing other then showing me a endless progressbar. This is consistent with google plus being broken or not working at all and news.google.com

**Comment by Caballlero** [comment]
Basically  i try to say is to use the webpirate code (if possible) to solve the rendering problems of some pages (mentioned above). this in order to improve webcat.

**Comment by Caballlero** [comment]
I speaking of webpirate in this thread because they have been brothers.  :  ) 
Make wc great llelectronics YouCan!

**Comment by llelectronics** [comment]
Ok figured out the issue I guess. It was no JS code that WebPirate had (we usually shared them anyway as soon as we found some cool new hack). It was pretty much that I broke it by adding clever code that catches on website loading if the cursor is set in a input or textbox to automatically show the keyboard. 
I somehow (had to be drunk there is no other explanation) thought it was a good idead to overwrite the whole window.onload javascript function instead of just adding the code necessary for the text input detection. 
Anyways fixed now with https://github.com/llelectronics/webcat/commit/a4342c7d8cb91137ced35333dca6579c6a259ffd

**Comment by Caballlero** [comment]
Tons of thanks..
 i will try now...

**Comment by Caballlero** [comment]
Yes fixed : ) Now feeling more  smooth

![captura_20170917_001](https://user-images.githubusercontent.com/24536606/30526045-64b4f01c-9be1-11e7-9c15-10819e85bf10.png)

**Comment by Caballlero** [comment]
**Acid3-Test**: **PASS**

![captura_20170917_002](https://user-images.githubusercontent.com/24536606/30526146-fd8a6c20-9be3-11e7-9fba-c0b8b1e372c5.png)

**Comment by Caballlero** [comment]
Also **maemo-talk layout** almost fixed with  a4342c7 by updating same thread.

**Comment by llelectronics** [comment]
Maemo Talk Layout can only be fixed I guess by putting it in the blacklist for the DevicePixelRatio. Or they ultimatively add a mobile theme to their site :P 
Anyways worked on integrating the rest of the Jolla/Mer patches into the QtWebkit package. Also tweaked a little bit on smoothness here and there and the Device Pixel Ratio Hack should work a tiny bit better now. The QtWebkit 5.212 package should be also now fully compatible with Jolla Settings.

**Comment by Caballlero** [comment]
wow; thx ; I wil try now.

**Comment by llelectronics** [comment]
It is still building though

**Comment by Caballlero** [comment]
- I know ; Thank you you very much. Also i wanna **try how is run Webcat on xperia x** , because there is a image with jamsanjoki, but i have several issue to get back to marshmallow  apparently it is a requirement to install  sailfish X, but I am in nougat.
My first idea is to enter recovery mode and do hard reset, but I can not find the way to get into recovery mode in sony xperia x, do you know how llelectroniscs

**Comment by llelectronics** [comment]
Uff you already have the Sailfish X Image? Hmm... I don't have that yet.

**Comment by Caballlero** [comment]
:  ) yeah. i am searching the link to send to you...

**Comment by llelectronics** [comment]
No hurry. I can still wait. After seeing the irc logs it isn't really ready anyways.

**Comment by Caballlero** [comment]
https://mega.nz/#F!BfpxWJxY!Q0RN21U7AJeg-quaJqC2cQ  It is for testing, But i can not wait more for testing llelectronics.

**Comment by Caballlero** [comment]
calls work , and much more...

**Comment by Caballlero** [comment]
It is already updated qtwebkit in obs? because look not updated.

**Comment by llelectronics** [comment]
Still building. Takes its time

**Comment by Caballlero** [comment]
Ok.. take you time.

**Comment by Caballlero** [comment]
I has been installed the new qtwebkit. Work much much much better, thx  = ) [ cursor point ] > fixed.

**Comment by Caballlero** [comment]
i installed Sailfish X or (xperia x ; port(aarch64) yesterday, i tried to install qtwebkit with webcat, but i was expecting the architecture incompatibility error. Just notifying...

**Comment by llelectronics** [comment]
For the architecture issue see this post: https://sailfishos.org/wiki/Sailfish_X_Build_and_Flash
At the end they mentioned to use rpm -ivh instead of pkcon install-local as root.

**Comment by Caballlero** [comment]
AHH! Thank you. 
You are already using sony xperia x with SFOS image?
I will test the new wc release on some changes in  user-agent, to check if facebook work.

**Comment by Caballlero** [comment]
Also a Sailfifh-podcast: On how install the new qtwebkit-engine to use with the new version of  Wecat 2.9.7  will much needed for end-users, they could confuse, or not knowing how to install the correct packages of new Qtwebkit-engine

**Comment by llelectronics** [comment]
It is not meant for end users yet. I really hope that Jolla will include qtwebkit officially in 2.1.4 or 2.1.5

**Comment by Caballlero** [comment]
Okay; Jolla has to accept your great work that you have done,  s o o n e r.
Thanks for ur nice work...

**Comment by Caballlero** [comment]
- I get install all the new Qtwebkit5.212 + Webcat with success.
[root@Sailfish full-qtwebkit5.212]# rpm -ivh *.rpm
Preparing...                ########################################### [100%]
	file /usr/lib/libQt5WebKitWidgets.so.5 from install of libqtwebkit5-widgets-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package libqtwebkit5-widgets-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/qt5/libexec/QtWebProcess from install of qt5-qtwebkit-uiprocess-launcher-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package qt5-qtwebkit-uiprocess-launcher-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/libQt5WebKit.so.5 from install of libqtwebkit5-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package libqtwebkit5-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/qt5/qml/QtWebKit/libqmlwebkitplugin.so from install of qt5-qtqml-import-webkitplugin-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package qt5-qtqml-import-webkitplugin-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/qt5/qml/QtWebKit/experimental/libqmlwebkitexperimentalplugin.so from install of qt5-qtqml-import-webkitplugin-experimental-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package qt5-qtqml-import-webkitplugin-experimental-5.6.2+git3-1.19.1.armv7hl
[root@Sailfish full-qtwebkit5.212]# rpm -ivh *.rpm -f
Preparing...                ########################################### [100%]
	file /usr/lib/libQt5WebKitWidgets.so.5 from install of libqtwebkit5-widgets-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package libqtwebkit5-widgets-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/qt5/libexec/QtWebProcess from install of qt5-qtwebkit-uiprocess-launcher-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package qt5-qtwebkit-uiprocess-launcher-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/libQt5WebKit.so.5 from install of libqtwebkit5-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package libqtwebkit5-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/qt5/qml/QtWebKit/libqmlwebkitplugin.so from install of qt5-qtqml-import-webkitplugin-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package qt5-qtqml-import-webkitplugin-5.6.2+git3-1.19.1.armv7hl
	file /usr/lib/qt5/qml/QtWebKit/experimental/libqmlwebkitexperimentalplugin.so from install of qt5-qtqml-import-webkitplugin-experimental-5.212.0-10.43.1.jolla.armv7hl conflicts with file from package qt5-qtqml-import-webkitplugin-experimental-5.6.2+git3-1.19.1.armv7hl
[root@Sailfish full-qtwebkit5.212]# rpm -ivh *.rpm --force
Preparing...                ########################################### [100%]
   1:qt5-qtwebkit-debugsourc########################################### [ 17%]
   2:libqtwebkit5-widgets   ########################################### [ 33%]
   3:qt5-qtwebkit-uiprocess-########################################### [ 50%]
   4:libqtwebkit5           ########################################### [ 67%]
   5:qt5-qtqml-import-webkit########################################### [ 83%]
   6:qt5-qtqml-import-webkit########################################### [100%]
[root@Sailfish Documents]# rpm -ivh harbour-webcat-2.9.12-1.armv7hl.rpm
Preparing...                ########################################### [100%]
1:harbour-webcat         ########################################### [100%]

- ** But webcat run choppy,not smoothes**
Just reporting to the **Webcat Database...**

**Comment by Caballlero** [comment]
Hello Lesner
Do you know if qtwebkit5.212 was accepted by jollla?

**Comment by llelectronics** [comment]
Just take a look here: https://git.merproject.org/mer-core/qtwebkit5/merge_requests/12
I don't see any progress there.

**Comment by Caballlero** [comment]
OK
I am totally disappointed with Jolla they never listen to the developers tremendous mistake of them because the developers are a super important part this case for sailfish OS. 
Sony xperia x is a disaster right now too <> Webcat is unusable

**Comment by llelectronics** [comment]
You need to talk to them directly by using the mer-meetings to get their attention. Otherwise the threads in together.jolla.com might be not seen or stuff postponed in urgency. 
So the last time I asked about QtWebkit they said they'll take a look into it and the TJC thread got a tracked by Jolla logo so I guess someone is taking a look into it fixing it. 

The problem with Jolla that it is a lot smaller company than it used to be. So getting this done is a lot harder especially if they don't only have to listen to users feedback but also have to create stuff for their customers and shareholders.

**Comment by Caballlero** [comment]
yeap, key-true-developers for sailfish OS are not already in jolla as **Mohammed Sameer - Marc Dillon - Rakko Rapola**

**Comment by Caballlero** [comment]
Hello Lesner
I see not progress on qtwebkit5212, it will be because you have a label of WIP ?
They still working on out date qtwebkit5.6 and pushing to qtwebkit5.6.4-on-mer-core.

**Comment by llelectronics** [comment]
I am not sure whats going on. I did not hear back from them at all. 
So I will leave everything as is for now. Jolla has not enough devs to maintain qtqwebkit as it seems.
They aren't even able to keep gecko up to date.

**Comment by Caballlero** [comment]
yes Gecko it is outdate too. I love SailfishOS but Jolla is stress me a lot.. I do not understand  why spend time or money on blockchain or something like that when the main sf-browser is causing pain to us. Anyway thanks Lesner for your nice work-on-SFOS

**Comment by Caballlero** [comment]
Hi Lesner
Confirmed SailfishOS 3.0 will come with  Qt5.9-WebEngine. So what is the future of webcat?

**Comment by llelectronics** [comment]
Oh you did confirm that in Barcelona? That would be nice. 
Not sure what the future of webcat then is. Webengine needs a redesigned browser and some features might get lost along the way.

Meanwhile I am working on an further upgraded Qt 5.212 release which I am still testing various tests with especially the Xperia X as it has some real struggles with qtwebkit for whatever reasons.

**Comment by Caballlero** [comment]
Yeap in Barcelona. Share your build of qtwebkit5212

**Comment by llelectronics** [comment]
As always the newest builds can be found here: https://build.merproject.org/package/show/home:leszek/qtwebkit5212-wHtml5Audio+Video

Only the html5 enabled is available for now.

**Comment by Caballlero** [comment]
I installed in jolla c, but not work. blank screen. Is this only xperia x? I first installed in jolla c .

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by llelectronics** [comment]
I am trying to fix issues with the Xperia X stutter that's why the current builds are broken.

**Comment by llelectronics** [comment]
Success: See my updated thread on tjc. Also added a openrepos repo for qtwebkit 5.212 
https://together.jolla.com/question/171114/xperia-xbug-qtwebkit-unusably-slow/?answer=180404#post-id-180404

**Comment by Caballlero** [comment]
Wow thanks Leszek  you are awesome. We need Leszek in jolla team.

**Comment by Caballlero** [comment]
Hi Hero-Dev

qtwebkit on openrepos is down

**Comment by Caballlero** [comment]
Leszek I have a big issue in all my device I can not upgrade to 2.1.4.14 via GUI. so I think that this issues is because I download the 2.1.4.14 before install qtwebkir5.212 , soo the solutions I think is reset the downloaded 2.1.4.14  but I do not know how? So I want to go in the folder into the system where is downloaded the  2.1.4.14 then delete manual, then download again the 2.1.4.xxx. I think this will fix my problem. So do you know where is the folder into the system Leszek?

**Comment by llelectronics** [comment]
Moved to a different repo: https://openrepos.net/content/llelectronicsdev/qtwebkit-5212-dev

As for the upgrade issue. Yeah this happens with my packages. You need to install the original qtwebkit packages. See Together.Jolla.com and the Openrepos instructions.

**Comment by Caballlero** [comment]
...with install the original qtwebkit packages it is not  fix upgrade issue if is already downloaded the image. So I Think is fix by deteleting manually the image then download again with  original qtwebkit. ** I do not find the folder **

**Comment by llelectronics** [comment]
That has nothing to do with it. Actually if you have the original qtwebkit packages installed and it is still failing to upgrade then you might have another package causing the conflict. 
Take a look at the log in /var/log/systemupdate.log and see if you can find any hints. 
The update is not downloading an image but the packages to upgrade to. The upgrade process when restarting and showing the minimal ui (minui) with the progressbar is actually the process of installing those rpm files. When it fails it usually means there is some kind of conflict.

**Comment by Caballlero** [comment]
thanks **Leszek** it is appreciable
I will check now, it is strage because is my first time with this issue in all my devices.

**Comment by Caballlero** [comment]
**Yeap you are correct**  is not really an image is only some packge to upgrade.  I do not know WTF  with packagekit-1.1.7 when I install  qtwebkit5.212 I get install without devel-su

**Comment by Caballlero** [comment]
I only see this 
24 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 20:33:29 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 20:33:32 Sailfish DSME[1425]: batterytracker: FAILED to read /run/state/namespaces/Battery/ChargePercentage
Mar 01 20:33:32 Sailfish DSME[1425]: batterytracker: FAILED to read /run/state/namespaces/Battery/IsCharging

**Comment by llelectronics** [comment]
To bad. Then you need to find out which third party rpm you might have installed that can cause this. Besides QtWebkit it can also be gstreamer (if you maybe installed one of my fixed versions for streaming for example)

**Comment by Caballlero** [comment]
**only show ytplayer** I already uninstalled

01 17:57:58 Sailfish sailfish-upgrade-ui[1438]: Package: harbour-ytplayer;0.5.4-1;armv7hl;store, Native YouTube client for SailfishOS
Mar 01 17:57:58 Sailfish PackageKit[1445]: upgrade-system transaction /1180_becaeecc from uid 0 finished with failed after 1669ms
Mar 01 17:57:58 Sailfish sailfish-upgrade-ui[1438]: Distribution upgrade error: Installation aborted by user
Mar 01 17:57:58 Sailfish sailfish-upgrade-ui[1438]: Upgrade completed with code 2
Mar 01 17:57:58 Sailfish sailfish-upgrade-ui[1438]: Reverting the enabled state of store to true
Mar 01 17:57:58 Sailfish PackageKit[1445]: uid 0 is trying to obtain org.freedesktop.packagekit.system-sources-configure auth (only_trusted:0)
Mar 01 17:57:58 Sailfish PackageKit[1445]: uid 0 obtained auth for org.freedesktop.packagekit.system-sources-configure
Mar 01 17:57:58 Sailfish PackageKit[1445]: repo-enable transaction /1181_ceaebdee from uid 0 finished with success after 13ms
Mar 01 17:57:58 Sailfish sailfish-upgrade-ui[1438]: Reverting the SSU version to 2.1.4.13
Mar 01 17:58:01 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:01 Sailfish mce[1411]: modules/proximity.c: report_proximity(): state: CLOSED -> OPEN
Mar 01 17:58:06 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:11 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:16 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:21 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:26 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:31 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:36 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:41 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:46 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:49 Sailfish DSME[1425]: batterytracker: FAILED to read /run/state/namespaces/Battery/ChargePercentage
Mar 01 17:58:49 Sailfish DSME[1425]: batterytracker: FAILED to read /run/state/namespaces/Battery/IsCharging
Mar 01 17:58:49 Sailfish DSME[1425]: batterytracker: No battery data available
Mar 01 17:58:51 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:58:56 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:59:01 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or directory
Mar 01 17:59:06 Sailfish mce[1411]: modules/battery-statefs.c: tracker_open(): /run/state/namespaces/Battery/State: open: No such file or direct

**Comment by Caballlero** [comment]
Any way I installed yesterday the fresh qtwebkit5.212 with Gstreamer to test then webcat feeling a lot smoother  I like it how feeling I  missed webcat on my xperia x  it now I can use it. thanks. It is almost 100% smoother. 
Also look this: https://git.merproject.org/mer-core/qtwebkit5/activity

**Comment by llelectronics** [comment]
It lists harbour-ytplayer as it seems. Maybe removing it will make the update work. 

And yes I saw that Jolla/Mer apparently took my patch and improved it for qtwebkit 5.6 before merging it :)

**Comment by Caballlero** [comment]
Packagekit is not downgrading package anymore automatically only upgrading this problem, I can get upgrade to 2.1..14 by terminal, but the GUI is not refresh still showing the update to upgrade.

**Comment by llelectronics** [comment]
If you updated manually via terminal you can remove the notification with 
`rm /home/nemo/.local/share/system/privileged/Notifications/notifications.db`

Needs a restart after that.

**Comment by Caballlero** [comment]
**Success** =  )  I fixed the xperia X of my woman with  your trick:  rm /home/nemo/.local/share/system/privileged/Notifications/notifications.db   This xperia X showed error to upgrade via GUI.
Still need fix my xperia  X I will check with same trick . 
So one more time **Many-Thanks Leszek**

**Comment by Caballlero** [comment]
**Success** Jolla c Fixed too = )
Note: Same case with xperia x issues.

**Comment by Caballlero** [comment]
**Failed**:   my own xperia X still failed to fix.
In this case I only upgraded my xperia X via terminal then was succcess to 2.1.4.14 . So the problem is that still show me that there is an update to 2.1.4.14  that it is already downloaded then need install it, But when I click to install this failed then show me an option to restart ,but when I click to restart this stay freezed so I need wait that the battery get over to restart the phone again . this freezed issue was  same in my woman-xperia, but that was fixed with your trick.

**Comment by llelectronics** [comment]
Don't wait for that battery to run out. Force restart with power button and one of the volume buttons holding for a few seconds. 

If upgrading via terminal and version --dup worked for you before try it here again it should work aswell. Don't forget to restart after the update finished.

**Comment by Caballlero** [comment]
What? I knowed force restart by long press power button. But never long press power buttom with volume. I knowed long-press-power-button-with-volume to Factory-Reset. Thanks I will use it if I need again. 
I already upgraded from 2.1.4.14 was launched, many time restarted. So the problem is just the info to upgrade. I am working to get the solution. One Solution  could be go to the folder where the packages of system are downloaded to delete manually then with your trick I think will fixed I guess :  )

**Comment by Caballlero** [comment]
To be more clear I already apply your trick on my xperia x then restart. but same the device still tell me than There is something to upgrade. I working  too on diferent step to get fix. 
Sorry for the bomb of messages here .

**Comment by Caballlero** [comment]
**Success** Fixed my xperia X. So I fixed all my devices with your  trick Example: rm /home/nemo/.local/share/system/privileged/Notifications/notifications.db 
Big Thanks  :  )
**Note**  Not was fixed on first time using the Trick: rm /home/nemo/.local/share/system/privileged/Notifications/notifications.db , because I still had one packages to downgrade/qt5* after that evething was fine. So the new pkcon reuse to downgrade packages in this case qtwebkit5.212 it is highter on the system. also Zypper showing more flexible on this. Thanks.

**Comment by Caballlero** [comment]
Then on this thread I think that if you change "**WIP: Qtwebkit5.212**" to "**Upgrade to "Qtwebkit5.212**" will much clear that is ready to merge.
Or maybe jolla is think that this qtwebkit5.212 is in alpha stage then not safe to merge. But the problem is that the current qtwebkit5.6 is obsolete too. So Alpha-Stage is much better that Obsolete-Stage. In fact  jolla need merge it your nice work.

**Comment by Caballlero** [comment]
Just Thanks...
