### ISSUE TITLE
Bookmark questions

### ISSUE THREAD

**Issue by wickedsp1d3r** [llelectronics/webcat#57]
Question 1:
In which file bookmarks are located?

Question 2:
I used "Delete All Bookmarks" function from the settings.
At next launch the default bookmarks are re-added. Why?

**Comment by llelectronics** [comment]
Answer 1: 
In a database located in ~/.local/share/harbour-webcat folder 

Answer 2:
This was a integrated feature request by a user. When you remove all bookmarks it comes up with the defaults again, resetting basically everything.
