### ISSUE TITLE
Port to Plasma Mobile

### ISSUE THREAD

**Issue by JLIT0** [llelectronics/webcat#58]
Have you considered a port to Plasma Mobile in consideration of the successful Librem 5 crowdfunding campaign?

**Comment by llelectronics** [comment]
It does not make much sense. KDE has already the Falkon browser based on QtWebengine. 
Also regarding all the problems I encountered with a QtWebkit based browser I think it might be wiser to use some other webengine like QtWebengine.

**Comment by JLIT0** [comment]
Ah, I understand.  Right now however, Falkon doesn't have a touch-friendly version available. Consequently, all Plasma builds seem to be using either Firefox, or more recently, Chromium, as the default browser - although these are desktop versions of the respective apps so are sub-optimal as well.

The original demo of Plasma Mobile showed the webbrowser-app from Ubuntu Touch being used.  However, this will not receive any new updates (unless UBports maintains [their fork of the application](https://github.com/ubports/webbrowser-app)).
