### ISSUE TITLE
Visually show that tor is configured as proxy

### ISSUE THREAD

**Issue by llelectronics** [llelectronics/webcat#62]
Show a onion on top of tab icon in toolbar when tor is configured as proxy.

**Comment by EarthlingX** [comment]
That would be really awesome! Maybe you can use those two icons and put them into this rectangular square where the number of tabs is displayed... 

![icon-settings-tor](https://user-images.githubusercontent.com/38689554/41345912-79474f2a-6ef4-11e8-95d6-601267a84ec3.png)
![icon-settings-tor-off](https://user-images.githubusercontent.com/38689554/41345914-79a8ec9e-6ef4-11e8-9e31-eadb57ff85c5.png)

**Comment by llelectronics** [comment]
Solved looks like this now: 
![screenshot_20180613_004](https://user-images.githubusercontent.com/3415572/41349824-6395c4aa-6f11-11e8-9a65-afea00395e90.png)
