### ISSUE TITLE
proxy not work

### ISSUE THREAD

**Issue by carlosgonzz** [llelectronics/webcat#64]
I can not use tor on webcat 3.0 | xperia x | 2.2 SF

**Comment by llelectronics** [comment]
It works here. 
What are the exact steps you did? 
And what is the error message?

**Comment by carlosgonzz** [comment]
![captura_20180629_001](https://user-images.githubusercontent.com/24536606/42121447-4ebda478-7bfd-11e8-810a-ab2397164c7b.png)

**Comment by llelectronics** [comment]
Not sure what you want to tell me with that terminal output. 
Can you answer my question of what exact steps you performed to enable tor proxy?
Do you have tor running as service already?
Webcat does not start Tor service. You need to start this manually.

**Comment by carlosgonzz** [comment]
![captura_20180630_001](https://user-images.githubusercontent.com/24536606/42127180-ea45d776-7c61-11e8-8606-c55a7bbcee38.png)
tor enabled by manually.

**Comment by carlosgonzz** [comment]
tor work ok on sailfish-browser but not in webcat, webcat is not listen proxy even enabled proxy.

**Comment by llelectronics** [comment]
I cannot reproduce this here. 
Did you restart webcat like it requested after setting a proxy?

**Comment by carlosgonzz** [comment]
yes I restart wc but same problem. was worked before this release. Is strange.

**Comment by llelectronics** [comment]
Tested it myself on various devices and also had some other users test it. Worked for me and worked for them aswell.
Not sure what is going wrong there for you.

**Comment by llelectronics** [comment]
Setting it as invalid for now as I need to be able to reproduce it to fix the issue.
