### ISSUE TITLE
custom userAgent not work

### ISSUE THREAD

**Issue by carlosgonzz** [llelectronics/webcat#65]
I can not personalize userAgent on webcat 3.0

**Comment by llelectronics** [comment]
It works here aswell. 
What were the steps you did?

**Comment by carlosgonzz** [comment]
when I tap in custom useragent is not permit me to delete the current useragent so when I tap custom useragent keyboard is not showed to edit the custom useragent

**Comment by llelectronics** [comment]
You have to choose custom and click on the area with the useragent string. You should be able to freely set the user agent then.

**Comment by carlosgonzz** [comment]
yes I did same how you say.

**Comment by llelectronics** [comment]
Then I don't see an issue

**Comment by carlosgonzz** [comment]
I say . I do how ur example but not work on my side . Very Very strange .this not work on 2 xperia x . I am  confident  than the -v3.0 in openrepos.net not work the issues I reported. I using webkit 5212 on 1 xperia x. the other xperia x is webkit-jolla, but same problem on both devices.

**Comment by carlosgonzz** [comment]
I have jolla c and jolla phone but I do not tested on these devices, because  I do not using ATM.

**Comment by llelectronics** [comment]
Setting as invalid for now. It needs to be reproducable otherwise I cannot fix it.
