### ISSUE TITLE
youtube not work

### ISSUE THREAD

**Issue by carlosgonzz** [llelectronics/webcat#66]
I can not see most of youtube video it is format error / forbbiden / or what ever.

**Comment by llelectronics** [comment]
In some regions Youtube requires you to login before you are able to see most Youtube videos. 
Other videos use DRM like vevo and others that isn't supported by Webcat.
I suggest using a third party youtube client for those that supports DRM.

**Comment by carlosgonzz** [comment]
login youtube it is just to verify the year old. with ytPlayer-youtube-dl all is good including DRM. built-in youtube-dl  into webcat will more pirate-browser which is nice : )

**Comment by llelectronics** [comment]
LLs video player is there for it. Youtube-DL integration into Webcat will not come as it brings problems when it comes to harbour compliance. 
I will not build in workarounds to trick harbour rules into accepting webcat like ytPlayer did.

**Comment by carlosgonzz** [comment]
I know on ur LLs Video Player-yt-dl but same problem :  ) 
Openrepos exist to go out of rules.

**Comment by llelectronics** [comment]
LLs videoplayer uses ytdl so if it has an issue with loading the youtube video maybe it isn't supported by ytdl or you need to update the ytdl binary from settings.

As for openrepos. I said it before I don't have time and patience to maintain two versions of webcat.

**Comment by carlosgonzz** [comment]
I understanded u.

**Comment by carlosgonzz** [comment]
LLsVideoPlayer show me almost same message error like webcat. so I can use this wonderful app. Look like that yt-dl is not decrypting  the video even having the decryptor(yt-dl) :  )
