### ISSUE TITLE
Whatsapp web doesn't load

### ISSUE THREAD

**Issue by saulhidalgoaular** [llelectronics/webcat#72]
Hello Leszek!!

First than all, Thanks for the good job!! webcat is an amazing browser.

Since we don't have whatsapp available in Sailfish OS, I was trying to launch the web version, but it doesn't load. 
https://web.whatsapp.com/
I have tried using Chromium and Firefox user agent, but it still doesn't load.
Is there anything I could do for fixing it?

Thanks.
Regards.
Saul

**Comment by llelectronics** [comment]
I fear this might not work because of the QtWebkit engine being too old. 
Have you tried it with my build of QtWebkit 5.212 from openrepos?

**Comment by llelectronics** [comment]
No answer so closing here.
